apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  ingressClassName: tailscale
  rules:
    - host: {{ .Values.tailscale.web }}
      http:
        paths:
          - backend:
              service:
                name: "{{ .Release.Name }}-web"
                port:
                  number: 8080
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.tailscale.web }}
