apiVersion: v1
kind: Namespace
metadata:
  name: argo-workflows
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  labels:
    argo/type: app
spec:
  project: default
  syncPolicy:
{{ .Values.syncPolicy | toYaml | indent 4 }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo-workflows
  source:
    repoURL: {{ .Values.repoURL }}
    path: argo-workflows/
    targetRevision: main
