apiVersion: v1
kind: Namespace
metadata:
  name: argo-cd
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  labels:
    argo/type: app
spec:
  project: default
  syncPolicy:
{{ .Values.syncPolicy | toYaml | indent 4 }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo-cd
  source:
    repoURL: {{ .Values.repoURL }}
    path: argo-cd/
    targetRevision: main
    helm:
      valuesObject:
        argo-cd:
          global:
            domain: "argo-cd.{{ .Values.tailnet }}"

          server:
            ingress:
              hostname: argo-cd
              extraTls:
                - hosts: ['argo-cd']
