apiVersion: v1
kind: Namespace
metadata:
  name: openspeedtest
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openspeedtest
  labels:
    argo/type: app
spec:
  project: default
  syncPolicy:
{{ .Values.syncPolicy | toYaml | indent 4 }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openspeedtest
  source:
    repoURL: {{ .Values.repoURL }}
    path: openspeedtest/
    targetRevision: main
