apiVersion: v1
kind: Namespace
metadata:
  name: pgadmin
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin
  labels:
    argo/type: app
spec:
  project: default
  syncPolicy:
{{ .Values.syncPolicy | toYaml | indent 4 }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: pgadmin
  source:
    repoURL: {{ .Values.repoURL }}
    path: pgadmin/
    targetRevision: main
