apiVersion: v1
kind: Namespace
metadata:
  name: pihole
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  labels:
    argo/type: app
spec:
  project: default
  syncPolicy:
{{ .Values.syncPolicy | toYaml | indent 4 }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: pihole
  source:
    repoURL: {{ .Values.repoURL }}
    path: pihole/
    targetRevision: main
    helm:
      valuesObject:
        pihole:
          dnsmasq:
            customDnsEntries:
              - "address=/pihole.{{ .Values.pihole.localDomainName }}/{{ .Values.pihole.piholeWebUiIp }}"

          extraEnvVars:
            FTLCONF_dns_domain: {{ .Values.pihole.localDomainName }}
            FTLCONF_webserver_domain: "pihole.{{ .Values.pihole.localDomainName }}"
            FTLCONF_dns_revServers: "true,{{ .Values.pihole.localReverseDns.localCidr }},{{ .Values.pihole.localReverseDns.dhcpDnsServer }},{{ .Values.pihole.localDomainName }}"

          virtualHost: pihole.{{ .Values.pihole.localDomainName }}
          ingress: # Use an ingress instead of serviceHttp
            enabled: true
            ingressClassName: traefik
            hosts:
              - pihole.{{ .Values.pihole.localDomainName }}
