apiVersion: v1
kind: Namespace
metadata:
  name: syncthing
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: syncthing
  labels:
    argo/type: app
spec:
  project: default
  syncPolicy:
{{ .Values.syncPolicy | toYaml | indent 4 }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: syncthing
  source:
    repoURL: {{ .Values.repoURL }}
    path: syncthing/
    targetRevision: main
