apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/enforce: privileged
  name: kube-flannel
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flannel
  labels:
    argo/type: infrastructure
spec:
  project: default
  syncPolicy:
{{ .Values.syncPolicy | toYaml | indent 4 }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-flannel
  source:
    repoURL: {{ .Values.repoURL }}
    path: infrastructure/flannel/
    targetRevision: main
