apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
  name: metallb
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  labels:
    argo/type: infrastructure
spec:
  project: default
  syncPolicy:
{{ .Values.syncPolicy | toYaml | indent 4 }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metallb
  ignoreDifferences:
    - group: '*'
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
  source:
    repoURL: {{ .Values.repoURL }}
    path: infrastructure/metallb/
    targetRevision: main
    helm:
      valuesObject:
{{ .Values.metallb | toYaml | indent 8 }}
