apiVersion: v1
kind: Namespace
metadata:
  name: pgo
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgo
  labels:
    argo/type: infrastructure
spec:
  project: default
  syncPolicy:
{{ .Values.syncPolicy | toYaml | indent 4 }}
    syncOptions:
    - Replace=true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: pgo
  source:
    repoURL: {{ .Values.repoURL }}
    path: infrastructure/pgo/
    targetRevision: main
