apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  labels:
    argo/type: infrastructure
spec:
  project: default
  syncPolicy:
{{ .Values.syncPolicy | toYaml | indent 4 }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tailscale
  source:
    repoURL: {{ .Values.repoURL }}
    path: infrastructure/tailscale/
    targetRevision: main
