apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  labels:
    argo/type: infrastructure
spec:
  project: default
  syncPolicy:
{{ .Values.syncPolicy | toYaml | indent 4 }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
  source:
    repoURL: {{ .Values.repoURL }}
    path: infrastructure/traefik/
    targetRevision: main
