{{- range $name, $pool := .Values.pools }}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ $name }}-pool
spec:
  addresses:
{{ $pool | toYaml | indent 4 }}
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ $name }}-advertisement
spec:
  ipAddressPools:
    - {{ $name }}-pool
{{- end }}
