image:
  repository: freshrss/freshrss
  tag: '1.28.1-alpine@sha256:0b029ab4cbd2b5772b3659ce9379a70ceec0b3a5326921748d07c724e57756e1'

timezone: Australia/Melbourne

tailscale:
  web: freshrss

cron:
  minute: '15,45'
