apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  config.json5: |-
    {
      "endpoint": "https://gitea.{{ .Values.tailnet }}/api/v1",
      "gitAuthor": "{{ .Values.renovate.gitAuthor }}",
      "platform": "gitea",
      "onboardingConfigFileName": "renovate.json",
      "autodiscover": true,
      "optimizeForDisabled": true,
      "onboardingConfig": {
        "$schema": "https://docs.renovatebot.com/renovate-schema.json",
        "extends": ["config:recommended"],
      },
    }
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: '{{ .Values.renovate.schedule }}'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate-bot
              # Update this to the latest available and then enable Renovate on the manifest
              image: '{{ .Values.renovate.image.repository }}:{{ .Values.renovate.image.tag }}'
              # Environment Variables
              env:
                - name: LOG_LEVEL
                  value: debug
                - name: RENOVATE_CONFIG_FILE
                  value: '/opt/renovate/config.json5'
              envFrom:
                - secretRef:
                    name: '{{ .Values.renovate.existingSecret }}'
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/
                - name: work-volume
                  mountPath: /tmp/renovate/
          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
            - name: work-volume
              emptyDir: {}
