argo-cd:
  global:
    image:
      repository: quay.io/argoproj/argocd
      tag: v3.0.11@sha256:1cb4ede2fc4a6332c128d9ba29d19e8cb5b76f9260dc47550a4b3b154269ff86

  configs:
    params:
      server.insecure: true

  server:
    service:
      servicePortHttp: 8080

    ingress:
      enabled: true
      ingressClassName: tailscale
