argo-cd:
  global:
    image:
      repository: quay.io/argoproj/argocd
      tag: v3.3.4@sha256:9f68a9a360ff65aaca66dfccf675219be73f0ac8c5c96797b6cb7760ee1b9056

  configs:
    params:
      applicationsetcontroller.policy: sync
      applicationsetcontroller.enable.progressive.syncs: false
      applicationsetcontroller.namespaces: ""
      application.namespaces: ""
      server.insecure: true

  server:
    service:
      servicePortHttp: 8080

    ingress:
      enabled: true
      ingressClassName: tailscale
