argo-cd:
  global:
    image:
      repository: quay.io/argoproj/argocd
      tag: v3.0.9@sha256:bdfe4d0cb6b04d43f1a310018275fe1ec9e023d917f0eda3c7bf4832f38edad4

  configs:
    params:
      server.insecure: true

  server:
    service:
      servicePortHttp: 8080

    ingress:
      enabled: true
      ingressClassName: tailscale
