argo-cd:
  global:
    image:
      repository: quay.io/argoproj/argocd
      tag: v3.0.6@sha256:a45307e2695d0fd93713e3d211b71086ac75a85dc8afbb28a249bdc4b3b0b2b9

  configs:
    params:
      server.insecure: true

  server:
    service:
      servicePortHttp: 8080

    ingress:
      enabled: true
      ingressClassName: tailscale
