image:
  registry: lscr.io
  repository: linuxserver/syncthing
  tag: '2.0.16@sha256:c15a770ebd879e729478638fee3a1ae383787ed2b923cb324bdab357e398a6b0'

tailscale:
  listener: syncthing
  webui: syncthing-webui
