image:
  registry: lscr.io
  repository: linuxserver/syncthing
  tag: '2.0.15@sha256:580ed2fe422253042da782cef634084e9868f7dcd449f5d6dd2b40e6e3a9dc13'

tailscale:
  listener: syncthing
  webui: syncthing-webui
