image:
  registry: lscr.io
  repository: linuxserver/syncthing
  tag: '2.0.15@sha256:befb3dc3efac8987270fa6fa99d9594a0dc2a11662b720a296453e162a274149'

tailscale:
  listener: syncthing
  webui: syncthing-webui
